//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UofAddinLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslatorRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslatorRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UofAddinLib.TranslatorRes", typeof(TranslatorRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte(s).
        /// </summary>
        internal static string ByteDesc {
            get {
                return ResourceManager.GetString("ByteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButtonTitle {
            get {
                return ResourceManager.GetString("CloseButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Loading Error.
        /// </summary>
        internal static string ConfigLoadError {
            get {
                return ResourceManager.GetString("ConfigLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configruration not found : oox2uof_package.
        /// </summary>
        internal static string ConfigOneNotFound {
            get {
                return ResourceManager.GetString("ConfigOneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Saving Error.
        /// </summary>
        internal static string ConfigSaveError {
            get {
                return ResourceManager.GetString("ConfigSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration no found: ooxml_version.
        /// </summary>
        internal static string ConfigThreeNotFound {
            get {
                return ResourceManager.GetString("ConfigThreeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configruration not found : ignore_error.
        /// </summary>
        internal static string ConfigTwoNotFound {
            get {
                return ResourceManager.GetString("ConfigTwoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation is over.Press the &quot;Close&quot; Button on the right-top edge of the Dialog to return to Word..
        /// </summary>
        internal static string EndPrompt {
            get {
                return ResourceManager.GetString("EndPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Target Folder.
        /// </summary>
        internal static string FolderSelectDialogTitle {
            get {
                return ResourceManager.GetString("FolderSelectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There may have been information and style lost during the translation. Press &quot;Detail&quot; Button  to see details..
        /// </summary>
        internal static string ForDetailPrompt {
            get {
                return ResourceManager.GetString("ForDetailPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to docx Format File.
        /// </summary>
        internal static string OoxFileTypeDesc {
            get {
                return ResourceManager.GetString("OoxFileTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors Occured During Translation.
        ///{0:D} of {1:D} File(s) Successfully Translated.
        ///Press &quot;See Log&quot; button to see the translation log..
        /// </summary>
        internal static string OpenFileWarning {
            get {
                return ResourceManager.GetString("OpenFileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Result.
        /// </summary>
        internal static string OpenFileWarningTitle {
            get {
                return ResourceManager.GetString("OpenFileWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some File(s) has been successfully translated.
        ///Would you like to open this file(s)?.
        /// </summary>
        internal static string OpenPartlyPrompt {
            get {
                return ResourceManager.GetString("OpenPartlyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt.
        /// </summary>
        internal static string OpenPartlyPromptTitle {
            get {
                return ResourceManager.GetString("OpenPartlyPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pptx Format File.
        /// </summary>
        internal static string PptxFileTypeDesc {
            get {
                return ResourceManager.GetString("PptxFileTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As docx Format File.
        /// </summary>
        internal static string SaveAsOoxDialogTitle {
            get {
                return ResourceManager.GetString("SaveAsOoxDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As pptx Format File.
        /// </summary>
        internal static string SaveAsPptxDialogTitle {
            get {
                return ResourceManager.GetString("SaveAsPptxDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As UOF Format File.
        /// </summary>
        internal static string SaveAsUofDialogTitle {
            get {
                return ResourceManager.GetString("SaveAsUofDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As xlsx Format File.
        /// </summary>
        internal static string SaveAsXlsxDialogTitle {
            get {
                return ResourceManager.GetString("SaveAsXlsxDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during file saving.
        ///Press &quot;See Log&quot; button to see the translation log..
        /// </summary>
        internal static string SaveFileError {
            get {
                return ResourceManager.GetString("SaveFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As UOF Format File Failed.
        /// </summary>
        internal static string SaveFileErrorTitle {
            get {
                return ResourceManager.GetString("SaveFileErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOF Format File.
        /// </summary>
        internal static string UOFFileTypeDesc {
            get {
                return ResourceManager.GetString("UOFFileTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xlsx Format File.
        /// </summary>
        internal static string XlsxFileTypeDesc {
            get {
                return ResourceManager.GetString("XlsxFileTypeDesc", resourceCulture);
            }
        }
    }
}
