//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UofCmdConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CmdConverterRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CmdConverterRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UofCmdConverter.CmdConverterRes", typeof(CmdConverterRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} already exists.Overwrite?(Y/N).
        /// </summary>
        internal static string FileAlreadyExistsPrompt {
            get {
                return ResourceManager.GetString("FileAlreadyExistsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find the file: .
        /// </summary>
        internal static string FileNotFoundPrompt {
            get {
                return ResourceManager.GetString("FileNotFoundPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your input is illegal. Please Answer y(yes) or n(no)..
        /// </summary>
        internal static string InputIllegalPrompt {
            get {
                return ResourceManager.GetString("InputIllegalPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -o is used to open UOF file.
        /// </summary>
        internal static string OpenUOFFilePrompt {
            get {
                return ResourceManager.GetString("OpenUOFFilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation failed..
        /// </summary>
        internal static string TranslationFailedPrompt {
            get {
                return ResourceManager.GetString("TranslationFailedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Succeed..
        /// </summary>
        internal static string TranslationSucceedPrompt {
            get {
                return ResourceManager.GetString("TranslationSucceedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:
        ///
        ///UofCmdConverter [option] [source file] [target file]
        ///
        ///Avaliable options:
        ///
        ///-o    Open an UOF document.
        ///       Set source file to the file you want to open.
        ///       Target file should be empty.
        ///
        ///-u2d Translate an UOF document to OpenXML document.
        ///
        ///-d2u Translate an OpenXML document to UOF document.
        ///
        ///Example:
        ///UofCmdConverter -o &quot;c:\\demo.uot&quot;
        ///UofCmdConverter -u2d &quot;c:\\demo.uot&quot; &quot;c:\\demo.docx&quot;.
        /// </summary>
        internal static string UsagePrompt {
            get {
                return ResourceManager.GetString("UsagePrompt", resourceCulture);
            }
        }
    }
}
