//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UofTranslatorActiveX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UofTranslatorActiveXRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UofTranslatorActiveXRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UofTranslatorActiveX.UofTranslatorActiveXRes", typeof(UofTranslatorActiveXRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL OpenXML -&gt; UOF2.0.
        /// </summary>
        internal static string ContextMenuALLOOXTOUOF {
            get {
                return ResourceManager.GetString("ContextMenuALLOOXTOUOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL UOF2.0 -&gt; OpenXML.
        /// </summary>
        internal static string ContextMenuALLUOFTOOOX {
            get {
                return ResourceManager.GetString("ContextMenuALLUOFTOOOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCX -&gt; UOF2.0.
        /// </summary>
        internal static string ContextMenuDOCXToUOF {
            get {
                return ResourceManager.GetString("ContextMenuDOCXToUOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenXML -&gt; UOF2.0.
        /// </summary>
        internal static string ContextMenuOOXToUOF {
            get {
                return ResourceManager.GetString("ContextMenuOOXToUOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPTX -&gt; UOF2.0.
        /// </summary>
        internal static string ContextMenuPPTXToUOF {
            get {
                return ResourceManager.GetString("ContextMenuPPTXToUOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOF2.0 -&gt; DOCX.
        /// </summary>
        internal static string ContextMenuUOFToDOCX {
            get {
                return ResourceManager.GetString("ContextMenuUOFToDOCX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOF2.0 -&gt; OpenXML.
        /// </summary>
        internal static string ContextMenuUOFToOOX {
            get {
                return ResourceManager.GetString("ContextMenuUOFToOOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOF2.0 -&gt; PPTX.
        /// </summary>
        internal static string ContextMenuUOFToPPTX {
            get {
                return ResourceManager.GetString("ContextMenuUOFToPPTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOF2.0 -&gt; XLSX.
        /// </summary>
        internal static string ContextMenuUOFToXLSX {
            get {
                return ResourceManager.GetString("ContextMenuUOFToXLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XLSX -&gt; UOF2.0.
        /// </summary>
        internal static string ContextMenuXLSXToUOF {
            get {
                return ResourceManager.GetString("ContextMenuXLSXToUOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ListColumnOne {
            get {
                return ResourceManager.GetString("ListColumnOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ListColumnTwo {
            get {
                return ResourceManager.GetString("ListColumnTwo", resourceCulture);
            }
        }
    }
}
