//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Act.UofTranslator.UofTranslatorStrictLib.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class message_zh_CHS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal message_zh_CHS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Act.UofTranslator.UofTranslatorStrictLib.resources.message-zh-CHS", typeof(message_zh_CHS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 段落中的边框线式样.
        /// </summary>
        internal static string Border_Style_in_Paragarph {
            get {
                return ResourceManager.GetString("Border_Style_in_Paragarph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首字母大写式样.
        /// </summary>
        internal static string Capital_Letter_Style_in_Paragraph {
            get {
                return ResourceManager.GetString("Capital_Letter_Style_in_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期信息.
        /// </summary>
        internal static string day_month_year_information_in_Paragraph {
            get {
                return ResourceManager.GetString("day_month_year_information_in_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 段落中的首字下沉式样.
        /// </summary>
        internal static string Dropcap_Style_in_Paragraph {
            get {
                return ResourceManager.GetString("Dropcap_Style_in_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 段落中的带圈字符式样.
        /// </summary>
        internal static string Enclose_Characters_in_Paragraph {
            get {
                return ResourceManager.GetString("Enclose_Characters_in_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尾注的重新开始编号式样.
        /// </summary>
        internal static string endnotePr_and_numRestart_in_Section {
            get {
                return ResourceManager.GetString("endnotePr_and_numRestart_in_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尾注位置信息.
        /// </summary>
        internal static string endnotePr_and_pos_in_Section {
            get {
                return ResourceManager.GetString("endnotePr_and_pos_in_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绕排表格的相对水平位置.
        /// </summary>
        internal static string floating_table_relative_horizontal_position_in_Table {
            get {
                return ResourceManager.GetString("floating_table_relative_horizontal_position_in_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绕排表格的相对水平位置.
        /// </summary>
        internal static string floating_table_relative_vertical_position_in_Table {
            get {
                return ResourceManager.GetString("floating_table_relative_vertical_position_in_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体类型.
        /// </summary>
        internal static string Font_Style {
            get {
                return ResourceManager.GetString("Font_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脚注的重新开始编号试样.
        /// </summary>
        internal static string footnotePr_and_numRestart_in_Section {
            get {
                return ResourceManager.GetString("footnotePr_and_numRestart_in_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脚注位置.
        /// </summary>
        internal static string footnotePr_and_pos_in_Section {
            get {
                return ResourceManager.GetString("footnotePr_and_pos_in_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高亮显示式样.
        /// </summary>
        internal static string Highlight_Style_in_Paragraph {
            get {
                return ResourceManager.GetString("Highlight_Style_in_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 段落中的对齐方式式样.
        /// </summary>
        internal static string Justification_Style_in_Paragraph {
            get {
                return ResourceManager.GetString("Justification_Style_in_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 节属性中的行号类型.
        /// </summary>
        internal static string lnNumType_and_lineType_in_Section_Properties {
            get {
                return ResourceManager.GetString("lnNumType_and_lineType_in_Section_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行号类型和行号重新开始式样.
        /// </summary>
        internal static string lnNumType_and_lnNumTypeRestart_in_Section_Properties {
            get {
                return ResourceManager.GetString("lnNumType_and_lnNumTypeRestart_in_Section_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编号格式.
        /// </summary>
        internal static string lvl_and_numFmt_in_Numbering {
            get {
                return ResourceManager.GetString("lvl_and_numFmt_in_Numbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编号与文字间的填充字符.
        /// </summary>
        internal static string lvl_and_suff_in_Numbering {
            get {
                return ResourceManager.GetString("lvl_and_suff_in_Numbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 节属性的编号格式.
        /// </summary>
        internal static string numFmt_and_val_in_Section_Properties {
            get {
                return ResourceManager.GetString("numFmt_and_val_in_Section_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页码格式和章节式样.
        /// </summary>
        internal static string pgNumType_and_chapStyle_in_Section {
            get {
                return ResourceManager.GetString("pgNumType_and_chapStyle_in_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拼音.
        /// </summary>
        internal static string Phonetic_Guide_Style_Paragraph {
            get {
                return ResourceManager.GetString("Phonetic_Guide_Style_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 段落,表格或文字的填充式样.
        /// </summary>
        internal static string shading_for_paragraphs_or_tables_or_phrases {
            get {
                return ResourceManager.GetString("shading_for_paragraphs_or_tables_or_phrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 某些复杂符号字符.
        /// </summary>
        internal static string Symbol_Characters_Paragraph {
            get {
                return ResourceManager.GetString("Symbol_Characters_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表格边框式样.
        /// </summary>
        internal static string table_border_style_in_Table {
            get {
                return ResourceManager.GetString("table_border_style_in_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 某些表格式样.
        /// </summary>
        internal static string Table_Style {
            get {
                return ResourceManager.GetString("Table_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 某些文字效果和数学公式.
        /// </summary>
        internal static string Text_Effect_or_Math_Formula_in_Paragraph {
            get {
                return ResourceManager.GetString("Text_Effect_or_Math_Formula_in_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 节属性的文字方向.
        /// </summary>
        internal static string textDirection_in_Section {
            get {
                return ResourceManager.GetString("textDirection_in_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题字体诗样.
        /// </summary>
        internal static string Theme_Font_Style {
            get {
                return ResourceManager.GetString("Theme_Font_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直合并单元格式样.
        /// </summary>
        internal static string vertically_merged_cell_in_Table {
            get {
                return ResourceManager.GetString("vertically_merged_cell_in_Table", resourceCulture);
            }
        }
    }
}
