//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Act.UofTranslator.UofTranslatorStrictLib.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class message_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal message_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Act.UofTranslator.UofTranslatorStrictLib.resources.message-en", typeof(message_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Style in Paragarph.
        /// </summary>
        internal static string Border_Style_in_Paragarph {
            get {
                return ResourceManager.GetString("Border_Style_in_Paragarph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital Letter Style in Paragraph.
        /// </summary>
        internal static string Capital_Letter_Style_in_Paragraph {
            get {
                return ResourceManager.GetString("Capital_Letter_Style_in_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day month year information in Paragraph.
        /// </summary>
        internal static string day_month_year_information_in_Paragraph {
            get {
                return ResourceManager.GetString("day_month_year_information_in_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropcap Style in Paragraph.
        /// </summary>
        internal static string Dropcap_Style_in_Paragraph {
            get {
                return ResourceManager.GetString("Dropcap_Style_in_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enclose Characters in Paragraph.
        /// </summary>
        internal static string Enclose_Characters_in_Paragraph {
            get {
                return ResourceManager.GetString("Enclose_Characters_in_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndnotePr and numRestart in Section.
        /// </summary>
        internal static string endnotePr_and_numRestart_in_Section {
            get {
                return ResourceManager.GetString("endnotePr_and_numRestart_in_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndnotePr and pos in Section.
        /// </summary>
        internal static string endnotePr_and_pos_in_Section {
            get {
                return ResourceManager.GetString("endnotePr_and_pos_in_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating table relative horizontal position in_Table.
        /// </summary>
        internal static string floating_table_relative_horizontal_position_in_Table {
            get {
                return ResourceManager.GetString("floating_table_relative_horizontal_position_in_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating table relative vertical position in Table.
        /// </summary>
        internal static string floating_table_relative_vertical_position_in_Table {
            get {
                return ResourceManager.GetString("floating_table_relative_vertical_position_in_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Style.
        /// </summary>
        internal static string Font_Style {
            get {
                return ResourceManager.GetString("Font_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FootnotePr and numRestart in Section.
        /// </summary>
        internal static string footnotePr_and_numRestart_in_Section {
            get {
                return ResourceManager.GetString("footnotePr_and_numRestart_in_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FootnotePr and pos in_Section.
        /// </summary>
        internal static string footnotePr_and_pos_in_Section {
            get {
                return ResourceManager.GetString("footnotePr_and_pos_in_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Style in Paragraph.
        /// </summary>
        internal static string Highlight_Style_in_Paragraph {
            get {
                return ResourceManager.GetString("Highlight_Style_in_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justification style in paragraph.
        /// </summary>
        internal static string Justification_Style_in_Paragraph {
            get {
                return ResourceManager.GetString("Justification_Style_in_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number Type and line Type in Section Properties.
        /// </summary>
        internal static string lnNumType_and_lineType_in_Section_Properties {
            get {
                return ResourceManager.GetString("lnNumType_and_lineType_in_Section_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number Type and lnNumTypeRestart in Section Properties.
        /// </summary>
        internal static string lnNumType_and_lnNumTypeRestart_in_Section_Properties {
            get {
                return ResourceManager.GetString("lnNumType_and_lnNumTypeRestart_in_Section_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number format in Numbering.
        /// </summary>
        internal static string lvl_and_numFmt_in_Numbering {
            get {
                return ResourceManager.GetString("lvl_and_numFmt_in_Numbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix of number in Numbering.
        /// </summary>
        internal static string lvl_and_suff_in_Numbering {
            get {
                return ResourceManager.GetString("lvl_and_suff_in_Numbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numberformat in Section Properties.
        /// </summary>
        internal static string numFmt_and_val_in_Section_Properties {
            get {
                return ResourceManager.GetString("numFmt_and_val_in_Section_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number type and chapter style in section properties.
        /// </summary>
        internal static string pgNumType_and_chapStyle_in_Section {
            get {
                return ResourceManager.GetString("pgNumType_and_chapStyle_in_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonetic Guide Style Paragraph.
        /// </summary>
        internal static string Phonetic_Guide_Style_Paragraph {
            get {
                return ResourceManager.GetString("Phonetic_Guide_Style_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shading for paragraphs or tables or phrases.
        /// </summary>
        internal static string shading_for_paragraphs_or_tables_or_phrases {
            get {
                return ResourceManager.GetString("shading_for_paragraphs_or_tables_or_phrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol Characters Paragraph.
        /// </summary>
        internal static string Symbol_Characters_Paragraph {
            get {
                return ResourceManager.GetString("Symbol_Characters_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table border style in Table.
        /// </summary>
        internal static string table_border_style_in_Table {
            get {
                return ResourceManager.GetString("table_border_style_in_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Style.
        /// </summary>
        internal static string Table_Style {
            get {
                return ResourceManager.GetString("Table_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Effect or Math Formula in Paragraph.
        /// </summary>
        internal static string Text_Effect_or_Math_Formula_in_Paragraph {
            get {
                return ResourceManager.GetString("Text_Effect_or_Math_Formula_in_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextDirection in Section.
        /// </summary>
        internal static string textDirection_in_Section {
            get {
                return ResourceManager.GetString("textDirection_in_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Font Style.
        /// </summary>
        internal static string Theme_Font_Style {
            get {
                return ResourceManager.GetString("Theme_Font_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertically merged cell in Table.
        /// </summary>
        internal static string vertically_merged_cell_in_Table {
            get {
                return ResourceManager.GetString("vertically_merged_cell_in_Table", resourceCulture);
            }
        }
    }
}
