//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UofStdConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StdConverterRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StdConverterRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UofStdConverter.StdConverterRes", typeof(StdConverterRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Target Folder.
        /// </summary>
        internal static string FolderSelectDialogTitle {
            get {
                return ResourceManager.GetString("FolderSelectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to docx Format File.
        /// </summary>
        internal static string OoxFileTypeDesc {
            get {
                return ResourceManager.GetString("OoxFileTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pptx Format File.
        /// </summary>
        internal static string PptxFileTypeDesc {
            get {
                return ResourceManager.GetString("PptxFileTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As docx Format File.
        /// </summary>
        internal static string SaveAsOoxDialogTitle {
            get {
                return ResourceManager.GetString("SaveAsOoxDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As pptx Format File.
        /// </summary>
        internal static string SaveAsPptxDialogTitle {
            get {
                return ResourceManager.GetString("SaveAsPptxDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As UOF Format File.
        /// </summary>
        internal static string SaveAsUofDialogTitle {
            get {
                return ResourceManager.GetString("SaveAsUofDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As xlsx Format File.
        /// </summary>
        internal static string SaveAsXlsxDialogTitle {
            get {
                return ResourceManager.GetString("SaveAsXlsxDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOF Format File.
        /// </summary>
        internal static string UOFFileTypeDesc {
            get {
                return ResourceManager.GetString("UOFFileTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xlsx Format File.
        /// </summary>
        internal static string XlsxFileTypeDesc {
            get {
                return ResourceManager.GetString("XlsxFileTypeDesc", resourceCulture);
            }
        }
    }
}
